// ============================================================================
// 11_sellers_data.js - DU LIEU SEED NHA BAN (AUTO-GENERATED)
//   Sinh boi: tools\BuildSellersSeed.java  <--  db/seed/sellers_real.txt
//   KHONG sua file nay bang tay. Muon sua ten: sua sellers_real.txt roi chay
//   tools\build-sellers-seed.bat
//   passwordHash la bcrypt THAT (cost 12) - dang nhap duoc bang email + mat khau.
// ============================================================================

const SELLERS = [
  { name: "Nhà xuất bản Trẻ", slug: "nha-xuat-ban-tre", email: "nhaxuatbantre@bookom.vn", password: "Nhaxuatbantre123@", hash: "$2a$12$rFR/rozQpIFwZvYEwR8oi.YdzD5ElDCRTJ4rijzACki2aqnAeXwkS" },
  { name: "Nhà xuất bản Kim Đồng", slug: "nha-xuat-ban-kim-dong", email: "nhaxuatbankimdong@bookom.vn", password: "Nhaxuatbankimdong123@", hash: "$2a$12$W5YH2I2.lea7/bU2ubvRYOnSzJ.PJyz2cSJ3a1euS9zjM7oDINcNy" },
  { name: "Nhà xuất bản Văn Học", slug: "nha-xuat-ban-van-hoc", email: "nhaxuatbanvanhoc@bookom.vn", password: "Nhaxuatbanvanhoc123@", hash: "$2a$12$f2TlkFfVnG9MGujZQRigDuBqH4Jn40yJ16tTr4V2Z8qIUMayBPNdO" },
  { name: "Nhà xuất bản Hội Nhà Văn", slug: "nha-xuat-ban-hoi-nha-van", email: "nhaxuatbanhoinhavan@bookom.vn", password: "Nhaxuatbanhoinhavan123@", hash: "$2a$12$bWq0d/PXq9Bw5mGwEiEAGeW0FxKQp3eXhPfefa44RPP4VgeFBU0R." },
  { name: "Nhà xuất bản Lao Động", slug: "nha-xuat-ban-lao-dong", email: "nhaxuatbanlaodong@bookom.vn", password: "Nhaxuatbanlaodong123@", hash: "$2a$12$0WtR.OaT6li6JwVZSeRbrese/u4y.QaROKrVS5rb9o9iyiS2eg5zm" },
  { name: "Nhà xuất bản Thanh Niên", slug: "nha-xuat-ban-thanh-nien", email: "nhaxuatbanthanhnien@bookom.vn", password: "Nhaxuatbanthanhnien123@", hash: "$2a$12$GL/OfomKbnlgXCzNIpJREuHxPPze3dvzeo7NFHhuHySvjDz7P8l9q" },
  { name: "Nhà xuất bản Phụ Nữ Việt Nam", slug: "nha-xuat-ban-phu-nu-viet-nam", email: "nhaxuatbanphunuvietnam@bookom.vn", password: "Nhaxuatbanphunuvietnam123@", hash: "$2a$12$EebV8.fPXwtmg04umIhSXu7caOlOVZpNgvBK8gd5EjXvm2G.QA.mm" },
  { name: "Nhà xuất bản Giáo Dục Việt Nam", slug: "nha-xuat-ban-giao-duc-viet-nam", email: "nhaxuatbangiaoducvietnam@bookom.vn", password: "Nhaxuatbangiaoducvietnam123@", hash: "$2a$12$LlCvCz6l33VPhzd12HPZBOvmaAeUeZWzunbSBwmW7mepGrhJZ8h.6" },
  { name: "Nhà xuất bản Đại Học Quốc Gia Hà Nội", slug: "nha-xuat-ban-dai-hoc-quoc-gia-ha-noi", email: "nhaxuatbandaihocquocgiahanoi@bookom.vn", password: "Nhaxuatbandaihocquocgiahanoi123@", hash: "$2a$12$BgT4uLOtHKyL0akTUN1S1e2reygm429NHoz7ynFE1lihJAbFwdCVi" },
  { name: "Nhà xuất bản Đại Học Quốc Gia Thành Phố Hồ Chí Minh", slug: "nha-xuat-ban-dai-hoc-quoc-gia-thanh-pho-ho-chi-minh", email: "nhaxuatbandaihocquocgiathanhphohochiminh@bookom.vn", password: "Nhaxuatbandaihocquocgiathanhphohochiminh123@", hash: "$2a$12$/PyqkhM5xB/ohfJCGnr48u3p1Y7ctK6Pns1kQ7zUQtBK9UPMT6Uhy" },
  { name: "Nhà xuất bản Tổng Hợp Thành Phố Hồ Chí Minh", slug: "nha-xuat-ban-tong-hop-thanh-pho-ho-chi-minh", email: "nhaxuatbantonghopthanhphohochiminh@bookom.vn", password: "Nhaxuatbantonghopthanhphohochiminh123@", hash: "$2a$12$M26YIbks7nZFOn0Mpeo7F.vF4quyKRLIevVioLXU/f7UQuQErKpaC" },
  { name: "Nhà xuất bản Chính Trị Quốc Gia Sự Thật", slug: "nha-xuat-ban-chinh-tri-quoc-gia-su-that", email: "nhaxuatbanchinhtriquocgiasuthat@bookom.vn", password: "Nhaxuatbanchinhtriquocgiasuthat123@", hash: "$2a$12$0RwRLwP5sfagNUCz71rFB.afh9KAEcX1h4aAUa8odJ11W9Rjr.Hl2" },
  { name: "Nhà xuất bản Thế Giới", slug: "nha-xuat-ban-the-gioi", email: "nhaxuatbanthegioi@bookom.vn", password: "Nhaxuatbanthegioi123@", hash: "$2a$12$4vZQ/DCNcwVHamZth3wDcuBBaY2/69.drKRnGOQDvhils1OyizZ8u" },
  { name: "Nhà xuất bản Tri Thức", slug: "nha-xuat-ban-tri-thuc", email: "nhaxuatbantrithuc@bookom.vn", password: "Nhaxuatbantrithuc123@", hash: "$2a$12$g8FuuWZ0p0gexUiPv9dOYO236b/KMF..rMnD3cuAQiCpEaocu/PvS" },
  { name: "Nhà xuất bản Khoa Học Xã Hội", slug: "nha-xuat-ban-khoa-hoc-xa-hoi", email: "nhaxuatbankhoahocxahoi@bookom.vn", password: "Nhaxuatbankhoahocxahoi123@", hash: "$2a$12$kxsvT3nyVlnwQogCpwD0j.W/d4NpX1qU1iE06Tofy/WwRrX92umaq" },
  { name: "Nhà xuất bản Kinh Tế Thành Phố Hồ Chí Minh", slug: "nha-xuat-ban-kinh-te-thanh-pho-ho-chi-minh", email: "nhaxuatbankinhtethanhphohochiminh@bookom.vn", password: "Nhaxuatbankinhtethanhphohochiminh123@", hash: "$2a$12$JHqxg.VtkexPZ0uBQDlv2O3aQB8WzGMsjnpx0kgX4cABxCK0AZw8C" },
  { name: "Nhà xuất bản Tài Chính", slug: "nha-xuat-ban-tai-chinh", email: "nhaxuatbantaichinh@bookom.vn", password: "Nhaxuatbantaichinh123@", hash: "$2a$12$JeeDBwmZ2nn7y2NL.AZnRuWA0fmCJOCO7hrPJLuQsXFcRe/BpTRS." },
  { name: "Nhà xuất bản Tư Pháp", slug: "nha-xuat-ban-tu-phap", email: "nhaxuatbantuphap@bookom.vn", password: "Nhaxuatbantuphap123@", hash: "$2a$12$2sLbRRk6HS/Msa.N5id7OeovTvkFtPzP8kY923rC0ic5F6tPqcGgK" },
  { name: "Nhà xuất bản Xây Dựng", slug: "nha-xuat-ban-xay-dung", email: "nhaxuatbanxaydung@bookom.vn", password: "Nhaxuatbanxaydung123@", hash: "$2a$12$bNcmXZjF1d1wx8/OD/MvAeVdhdXaLpjB0.UNPv3aY9tZi5cfz3qMi" },
  { name: "Nhà xuất bản Giao Thông Vận Tải", slug: "nha-xuat-ban-giao-thong-van-tai", email: "nhaxuatbangiaothongvantai@bookom.vn", password: "Nhaxuatbangiaothongvantai123@", hash: "$2a$12$NoV/VnNSTFZXFUyzRuuwdeCvaM9Cx9PFsTOUyS4Gms/3TBGqELFWu" },
  { name: "Nhà xuất bản Khoa Học Kỹ Thuật", slug: "nha-xuat-ban-khoa-hoc-ky-thuat", email: "nhaxuatbankhoahockythuat@bookom.vn", password: "Nhaxuatbankhoahockythuat123@", hash: "$2a$12$U6JxFdpEjdJaaHClNnw/xOCd5agqqy7Dl7zGMr9Iziefp6MLzcYeO" },
  { name: "Nhà xuất bản Nông Nghiệp", slug: "nha-xuat-ban-nong-nghiep", email: "nhaxuatbannongnghiep@bookom.vn", password: "Nhaxuatbannongnghiep123@", hash: "$2a$12$lTV8vFiPa9oUIC/lcTShp.29QrCe4AThk9.zWMcHFnVwfQBRLN9ES" },
  { name: "Nhà xuất bản Y Học", slug: "nha-xuat-ban-y-hoc", email: "nhaxuatbanyhoc@bookom.vn", password: "Nhaxuatbanyhoc123@", hash: "$2a$12$KQCxaFhCoLaqM6MizPYmAOMI8zEPa1BWmdrrOWyWi2XNBluN26e3." },
  { name: "Nhà xuất bản Thông Tin và Truyền Thông", slug: "nha-xuat-ban-thong-tin-va-truyen-thong", email: "nhaxuatbanthongtinvatruyenthong@bookom.vn", password: "Nhaxuatbanthongtinvatruyenthong123@", hash: "$2a$12$JCWTJwVkai4U9Kuk8qHwsuJbtkFv23Q94O.zFKJPBXlAkBt9bRunS" },
  { name: "Nhà xuất bản Bản Đồ", slug: "nha-xuat-ban-ban-do", email: "nhaxuatbanbando@bookom.vn", password: "Nhaxuatbanbando123@", hash: "$2a$12$0oX.ZjufKZFwth21yx9b/ulv3w2VWTKkQ/BfoAYQAdemth7rCcGUe" },
  { name: "Nhà xuất bản Đà Nẵng", slug: "nha-xuat-ban-da-nang", email: "nhaxuatbandanang@bookom.vn", password: "Nhaxuatbandanang123@", hash: "$2a$12$nw7RLsrop5hBax.ohwpipOy5lwxZa2iZEtHsR0fAls0JDCbJdl0fq" },
  { name: "Nhà xuất bản Thuận Hóa", slug: "nha-xuat-ban-thuan-hoa", email: "nhaxuatbanthuanhoa@bookom.vn", password: "Nhaxuatbanthuanhoa123@", hash: "$2a$12$zV3mPR1KTbtZBUOdZilRWeRM8LziBiUa9QkpwrfAe2ZX/23.l.oZO" },
  { name: "Nhà xuất bản Hồng Đức", slug: "nha-xuat-ban-hong-duc", email: "nhaxuatbanhongduc@bookom.vn", password: "Nhaxuatbanhongduc123@", hash: "$2a$12$sbx7ifDZnW9aEZec9TW3tu932FPRnvK8F8miAr1R/Uqzr9x/4qTxO" },
  { name: "Nhà xuất bản Dân Trí", slug: "nha-xuat-ban-dan-tri", email: "nhaxuatbandantri@bookom.vn", password: "Nhaxuatbandantri123@", hash: "$2a$12$TyRCf2vi29MyUPnPAJvUEuZXh9Z1dwhT.LKjWMyUdqeGONhP7/3My" },
  { name: "Nhà xuất bản Công Thương", slug: "nha-xuat-ban-cong-thuong", email: "nhaxuatbancongthuong@bookom.vn", password: "Nhaxuatbancongthuong123@", hash: "$2a$12$L/kyAPpAUomqx48RGFsZPO6W8eOXJhaI1JA/zJfQi349vyWwS5ea2" },
  { name: "Nhà xuất bản Quân Đội Nhân Dân", slug: "nha-xuat-ban-quan-doi-nhan-dan", email: "nhaxuatbanquandoinhandan@bookom.vn", password: "Nhaxuatbanquandoinhandan123@", hash: "$2a$12$iZwmib18eaPkmKlSuNhW9uq9jmoEHwne42dRGWbChKE/QGtd3tztq" },
  { name: "Nhà xuất bản Công An Nhân Dân", slug: "nha-xuat-ban-cong-an-nhan-dan", email: "nhaxuatbancongannhandan@bookom.vn", password: "Nhaxuatbancongannhandan123@", hash: "$2a$12$XG4E5El74bjK8HPX83OxTe6abxm20iQZ7.BnCjFISgboywiPAR6Se" },
  { name: "Nhà xuất bản Văn Hóa Nghệ Thuật", slug: "nha-xuat-ban-van-hoa-nghe-thuat", email: "nhaxuatbanvanhoanghethuat@bookom.vn", password: "Nhaxuatbanvanhoanghethuat123@", hash: "$2a$12$flbdRg9AyRKkeWJTChD52.OFiCDHwxzWXUb/r7LYz8ejDthaB7Qi." },
  { name: "Nhà xuất bản Đại Học Sư Phạm Hà Nội", slug: "nha-xuat-ban-dai-hoc-su-pham-ha-noi", email: "nhaxuatbandaihocsuphamhanoi@bookom.vn", password: "Nhaxuatbandaihocsuphamhanoi123@", hash: "$2a$12$gbKsY0f9GErXTwnGCGdeVOSoTR0j/roijD3RtblE6tqB6plEj93Pe" },
  { name: "Nhà xuất bản Đại Học Sư Phạm Thành Phố Hồ Chí Minh", slug: "nha-xuat-ban-dai-hoc-su-pham-thanh-pho-ho-chi-minh", email: "nhaxuatbandaihocsuphamthanhphohochiminh@bookom.vn", password: "Nhaxuatbandaihocsuphamthanhphohochiminh123@", hash: "$2a$12$RoXXOjvVbcds4yr0mIShq.Ub04gubW4rJSLSRC5Mp5hoKLzIMqJ0C" },
  { name: "Nhà xuất bản Bách Khoa Hà Nội", slug: "nha-xuat-ban-bach-khoa-ha-noi", email: "nhaxuatbanbachkhoahanoi@bookom.vn", password: "Nhaxuatbanbachkhoahanoi123@", hash: "$2a$12$ogNFF3n3bTmN02rI9jp6wO4XiN1NVcN95rv/mNmqWn3L13cE.bWG." },
  { name: "Nhà xuất bản Từ Điển Bách Khoa", slug: "nha-xuat-ban-tu-dien-bach-khoa", email: "nhaxuatbantudienbachkhoa@bookom.vn", password: "Nhaxuatbantudienbachkhoa123@", hash: "$2a$12$rRhCzWHKTYpKxgezaWW8pOBuZKaiXNFLCnQ/H45aL7R9R6R8r420e" },
  { name: "Nhà xuất bản Văn Hóa Thông Tin", slug: "nha-xuat-ban-van-hoa-thong-tin", email: "nhaxuatbanvanhoathongtin@bookom.vn", password: "Nhaxuatbanvanhoathongtin123@", hash: "$2a$12$f58YLWRT7Pazt8CEGzDqGO.AAK8FIg33SCHIXZ1H4MRMByE5vdgR2" },
  { name: "Nhà xuất bản Thanh Hóa", slug: "nha-xuat-ban-thanh-hoa", email: "nhaxuatbanthanhhoa@bookom.vn", password: "Nhaxuatbanthanhhoa123@", hash: "$2a$12$cfwf5/HgOtg25IFEfM2yru96DJVw3Ol9VkbVhkb9X5Zw2UUJvdhX2" },
  { name: "Nhà xuất bản Nghệ An", slug: "nha-xuat-ban-nghe-an", email: "nhaxuatbannghean@bookom.vn", password: "Nhaxuatbannghean123@", hash: "$2a$12$FCpl2FQb6KY9GqyFmL3iCuc/L8SvUxjSn5ZkxMGDRUtMtvVgPOXxG" },
  { name: "Nhà xuất bản Hà Nội", slug: "nha-xuat-ban-ha-noi", email: "nhaxuatbanhanoi@bookom.vn", password: "Nhaxuatbanhanoi123@", hash: "$2a$12$u7lq5q1sgCs7U4cgpZzE/.DsV/kuLMEcdyONMlWIyvk9D2XfkidpK" },
  { name: "Nhà xuất bản Hải Phòng", slug: "nha-xuat-ban-hai-phong", email: "nhaxuatbanhaiphong@bookom.vn", password: "Nhaxuatbanhaiphong123@", hash: "$2a$12$mUmTJGLt4H/KzoG/byasLeY7z5fHmAYpiTRYttdtIul7VQ3EJW3PC" },
  { name: "Nhà xuất bản Cần Thơ", slug: "nha-xuat-ban-can-tho", email: "nhaxuatbancantho@bookom.vn", password: "Nhaxuatbancantho123@", hash: "$2a$12$sz9gu36zMhb75RXzO2oDaevauFWytLhJQu2YVR/CSyjg0bxMl6ybO" },
  { name: "Nhà xuất bản An Giang", slug: "nha-xuat-ban-an-giang", email: "nhaxuatbanangiang@bookom.vn", password: "Nhaxuatbanangiang123@", hash: "$2a$12$RiSO7Tq6B5CCvxwRoN7GKOZa0a1p.ANE5pCguxihBP/cDQ.nML5Om" },
  { name: "Nhà xuất bản Đồng Nai", slug: "nha-xuat-ban-dong-nai", email: "nhaxuatbandongnai@bookom.vn", password: "Nhaxuatbandongnai123@", hash: "$2a$12$0zkVpRUevIekp8w4JNgqp.rCA/OB0CjBlqYDVw24jpARyIrm60HGm" },
  { name: "Nhà xuất bản Long An", slug: "nha-xuat-ban-long-an", email: "nhaxuatbanlongan@bookom.vn", password: "Nhaxuatbanlongan123@", hash: "$2a$12$n0q.8lnJXBkX0LuAi470uOVn1pcoydYYGgv/nn74CM8ofTbOFtJLW" },
  { name: "Nhà xuất bản Bình Định", slug: "nha-xuat-ban-binh-dinh", email: "nhaxuatbanbinhdinh@bookom.vn", password: "Nhaxuatbanbinhdinh123@", hash: "$2a$12$r4QbFmOA6zPdkCw54MSES.9DGYmgWIdqUKgqDauISiJ4E8Xnfigfa" },
  { name: "Nhà xuất bản Phương Đông", slug: "nha-xuat-ban-phuong-dong", email: "nhaxuatbanphuongdong@bookom.vn", password: "Nhaxuatbanphuongdong123@", hash: "$2a$12$c78QaGvdjqDo2DOu0xiYku7UpKJjurVhhbIc0ggjepihyI22MnCSW" },
  { name: "Nhà xuất bản Văn Hiến", slug: "nha-xuat-ban-van-hien", email: "nhaxuatbanvanhien@bookom.vn", password: "Nhaxuatbanvanhien123@", hash: "$2a$12$Obvz2TrGCVhstyIFxM3MT.qL3cOEbvtQGh.vniwm0pfbJHOUXewP2" },
  { name: "Nhà xuất bản Thông Tấn", slug: "nha-xuat-ban-thong-tan", email: "nhaxuatbanthongtan@bookom.vn", password: "Nhaxuatbanthongtan123@", hash: "$2a$12$KNOUSuxBO3MNicphwEylQ.ludWwULptBLTWfiRikbF9Z5yp9K6UHi" },
  { name: "Nhã Nam", slug: "nha-nam", email: "nhanam@bookom.vn", password: "Nhanam123@", hash: "$2a$12$2GhwUJTA5EVbO8ufxG00YO.RT3mt9jlZRWBTDwfvwD/2xVyBOAyVW" },
  { name: "Nhà sách Đại Nam", slug: "nha-sach-dai-nam", email: "nhasachdainam@bookom.vn", password: "Nhasachdainam123@", hash: "$2a$12$Nt25EBCuPNtfAHy56NTvLOBkPC9przRIM7XgAUSavK0gJuWyOkBnG" },
  { name: "Fahasa", slug: "fahasa", email: "fahasa@bookom.vn", password: "Fahasa123@", hash: "$2a$12$zwZCW..JofVxKOoeqwA1MeLlcIfRVSxtFq9d2f5ZcGV6dijWaGbOC" },
  { name: "Phương Nam Book", slug: "phuong-nam-book", email: "phuongnambook@bookom.vn", password: "Phuongnambook123@", hash: "$2a$12$Q1D9E5.gHq.I9Pn3xy6V.eIFtN2Crle4QvS9fXK/t6E9b7R0gr4X." },
  { name: "Thái Hà Books", slug: "thai-ha-books", email: "thaihabooks@bookom.vn", password: "Thaihabooks123@", hash: "$2a$12$tH5ovHqDarDTNb5h5HWbo.i0ZYxPrMDf0R9N2hMpyuClt0Am42Izy" },
  { name: "Alphabooks", slug: "alphabooks", email: "alphabooks@bookom.vn", password: "Alphabooks123@", hash: "$2a$12$epb7EfB0p3wsxtAwhxurZ.qCZCatQJMiBsf/Y4H2ag9dKQ9Y244eK" },
  { name: "Omega Plus", slug: "omega-plus", email: "omegaplus@bookom.vn", password: "Omegaplus123@", hash: "$2a$12$oQEnZGMrGn86vsyzj5VMF.JJwfhTyDu5jRqLadJDgiYPZhB9/JSGi" },
  { name: "Đông A", slug: "dong-a", email: "donga@bookom.vn", password: "Donga123@", hash: "$2a$12$T8INhCTL8BMLRXIQ.mmlx.dWqliWQW.8dorZMUjfcW9bKMLUbxR3m" },
  { name: "Nhà sách Cá Chép", slug: "nha-sach-ca-chep", email: "nhasachcachep@bookom.vn", password: "Nhasachcachep123@", hash: "$2a$12$hSCu7UIrCzJnLjDkIVyJzeKy04j2vyUWMmhnSMtaI.jCyIWP/EI3i" },
  { name: "Hải An Book", slug: "hai-an-book", email: "haianbook@bookom.vn", password: "Haianbook123@", hash: "$2a$12$jAZRKpejlvaYx9eE8gLJleQduTfjsI2LQpcQDcwBEFok26/8FA9li" },
  { name: "MCBooks", slug: "mcbooks", email: "mcbooks@bookom.vn", password: "Mcbooks123@", hash: "$2a$12$Nyn2w7DUyzYkinLCgzIQcutO0.02eTahbjMn.22VoBxcJ.9BH8Z0W" },
  { name: "1980 Books", slug: "1980-books", email: "1980books@bookom.vn", password: "1980books123@", hash: "$2a$12$ndsp9EGd8qwZwjwLOo6wyOlp1.vRG76FMdKgx/ST66zVBAoFxolru" },
  { name: "BizBooks", slug: "bizbooks", email: "bizbooks@bookom.vn", password: "Bizbooks123@", hash: "$2a$12$I7n9/5E6yo1ZoGN0uVLptuO.4CXYAcdbYYWFmEQccZdAv.qQPhrre" },
  { name: "PandaBooks", slug: "pandabooks", email: "pandabooks@bookom.vn", password: "Pandabooks123@", hash: "$2a$12$meSgmePJ2jZSUpnpck8v6.sRNXyyF2PtmnD3IyPyoPYFZTgUpA02C" },
  { name: "Vinabook", slug: "vinabook", email: "vinabook@bookom.vn", password: "Vinabook123@", hash: "$2a$12$7el3T7HT5sGKilA38CTxT.OLs3QHHHON8Q19wUpPQm5uggfFjqbTq" },
  { name: "Nhà sách Minh Khai", slug: "nha-sach-minh-khai", email: "nhasachminhkhai@bookom.vn", password: "Nhasachminhkhai123@", hash: "$2a$12$ZAj234fuJdi5rcNfPo/4P.OtBvtVVMWn8MSFqdYLNmEi0BuGozEZq" },
  { name: "Nhà sách Bình Tây", slug: "nha-sach-binh-tay", email: "nhasachbinhtay@bookom.vn", password: "Nhasachbinhtay123@", hash: "$2a$12$au46/5aBIeDW27UXBw4HtuMc543azfbFzAZzINxwmYxvqzArQkeYy" },
  { name: "Nhà sách Khai Trí", slug: "nha-sach-khai-tri", email: "nhasachkhaitri@bookom.vn", password: "Nhasachkhaitri123@", hash: "$2a$12$bm9X4gg4rQMXtyDRMRQlm.g2AW9/9qMeLXrTinyM766PBpnhG/k8e" },
  { name: "Nhà sách Xuân Thu", slug: "nha-sach-xuan-thu", email: "nhasachxuanthu@bookom.vn", password: "Nhasachxuanthu123@", hash: "$2a$12$kri.0J0IaOnXmWPD57VAzeElkksV2.U6lSCJKShg679At59e4jjiO" },
  { name: "Nhà sách Thăng Long", slug: "nha-sach-thang-long", email: "nhasachthanglong@bookom.vn", password: "Nhasachthanglong123@", hash: "$2a$12$ANKHVC1gp0wxGay7TodysO231nIab323aHOEbwuz5ILAMFoGcKdLu" },
  { name: "Nhà sách Trí Tuệ", slug: "nha-sach-tri-tue", email: "nhasachtritue@bookom.vn", password: "Nhasachtritue123@", hash: "$2a$12$542S1SF/Anc5FUba0rkCk.OgVv5tOdVRURhQ0LmWRmD5Ccpe6fV/u" },
  { name: "Nhà sách Hồng Ân", slug: "nha-sach-hong-an", email: "nhasachhongan@bookom.vn", password: "Nhasachhongan123@", hash: "$2a$12$YR8hq6S2DnonQc7cA9tVgegcf8Vqds8I5VxbEC9WjlHFg9CWoB5rm" },
  { name: "Nhà sách Vĩnh Thịnh", slug: "nha-sach-vinh-thinh", email: "nhasachvinhthinh@bookom.vn", password: "Nhasachvinhthinh123@", hash: "$2a$12$OAukOATZ84KU8FD.pX6/au198pI2RAPFiWQN4OuylAhCsDDbNYZfm" },
  { name: "Nhà sách Kim Mã", slug: "nha-sach-kim-ma", email: "nhasachkimma@bookom.vn", password: "Nhasachkimma123@", hash: "$2a$12$Bs9Qr0nUPtUUBMQ4CdQqZOtCb8D2mL4ZAxClP2CPyXyzBEqfepLuS" },
  { name: "Nhà sách Sài Gòn", slug: "nha-sach-sai-gon", email: "nhasachsaigon@bookom.vn", password: "Nhasachsaigon123@", hash: "$2a$12$EnwstDjDI0TItgFe0CgOHOLngRSj5hDfZ7nYsEL7RxmJ4jvt.VyNy" },
  { name: "Nhà sách Vạn Hạnh", slug: "nha-sach-van-hanh", email: "nhasachvanhanh@bookom.vn", password: "Nhasachvanhanh123@", hash: "$2a$12$to3eKmqgVD3UXmaKJvHh4uVyqxBv11jl.kb2FiBpqlbbMlVJtXtEG" },
  { name: "Nhà sách Á Châu", slug: "nha-sach-a-chau", email: "nhasachachau@bookom.vn", password: "Nhasachachau123@", hash: "$2a$12$8Bfjy5PZJj5/NbaMAbHU4.FoZxSQF577K8MVOjqPmzDLIrw2yAbxy" },
  { name: "Nhà sách Nhân Văn", slug: "nha-sach-nhan-van", email: "nhasachnhanvan@bookom.vn", password: "Nhasachnhanvan123@", hash: "$2a$12$U9nDNzQQND53RPcfewx7d.ymb6efLQRJlNUW8Dm04CaIVUOS3BSs2" },
  { name: "Nhà sách Phú Thọ", slug: "nha-sach-phu-tho", email: "nhasachphutho@bookom.vn", password: "Nhasachphutho123@", hash: "$2a$12$jIcfJD4bfqhv1plH8gOFV.iVRe9K7pttRBjno7dLbv5A4Bz9ne1Jq" },
  { name: "Nhà sách TriBooks", slug: "nha-sach-tribooks", email: "nhasachtribooks@bookom.vn", password: "Nhasachtribooks123@", hash: "$2a$12$OHhW4tNu2wxVMWrSViTofeDf4iGyCA3OCbzCyx3N/ZwsqRkya1Jwe" },
  { name: "Nhà sách Văn Lang", slug: "nha-sach-van-lang", email: "nhasachvanlang@bookom.vn", password: "Nhasachvanlang123@", hash: "$2a$12$/feTVTia0Dk.wFryneOnk.M1RnXoIHenxtcp9lcYE9WLnSns.PzrS" },
  { name: "Nhà sách Bảo Nam", slug: "nha-sach-bao-nam", email: "nhasachbaonam@bookom.vn", password: "Nhasachbaonam123@", hash: "$2a$12$osj3p8.hRxFSilUyuQF2C.4Cdf2WxGYSIUP4MOSA.6cn0iCq68APK" },
  { name: "Nhà sách Thanh Niên", slug: "nha-sach-thanh-nien", email: "nhasachthanhnien@bookom.vn", password: "Nhasachthanhnien123@", hash: "$2a$12$wiHq2uHkVlGpiz8L/opTZumVnLe4XDd3XSiVECkzZXweyqTJmkGXy" },
  { name: "Nhà sách Tân Việt", slug: "nha-sach-tan-viet", email: "nhasachtanviet@bookom.vn", password: "Nhasachtanviet123@", hash: "$2a$12$7lmCotHayFfACNXaFRjVbukVW348NK2DxuIBTmaf6voIv2rSansK6" },
  { name: "Nhà sách Nguyễn Văn Cừ", slug: "nha-sach-nguyen-van-cu", email: "nhasachnguyenvancu@bookom.vn", password: "Nhasachnguyenvancu123@", hash: "$2a$12$yGdnGk0kYRV1K/BjZstiUeNpvnnvn5BObarQNL7YU9zvtzv2x0gr." },
  { name: "Nhà sách Tuyết Mai", slug: "nha-sach-tuyet-mai", email: "nhasachtuyetmai@bookom.vn", password: "Nhasachtuyetmai123@", hash: "$2a$12$2.O.7ybBXYI3vMO8PZPLlOJnkOLg4CUyytIFnb2p8aDMGqjNB3X/q" },
  { name: "Nhà sách Phương Đông", slug: "nha-sach-phuong-dong", email: "nhasachphuongdong@bookom.vn", password: "Nhasachphuongdong123@", hash: "$2a$12$Dy.Vl9KdvqtpyfgsxtjI8uWyzL8DfLRJnIZso6kkHp9pfvZNyrpgu" },
  { name: "Nhà sách Hà Nội", slug: "nha-sach-ha-noi", email: "nhasachhanoi@bookom.vn", password: "Nhasachhanoi123@", hash: "$2a$12$ZrIAck9WG92fSXS08NhCF.2DCWecvulsiQ17SWczukhU.MvX0IQVu" },
  { name: "Nhà sách Tràng Tiền", slug: "nha-sach-trang-tien", email: "nhasachtrangtien@bookom.vn", password: "Nhasachtrangtien123@", hash: "$2a$12$uh7RfpQCeO3Kq6yTVvOeeOoHJnLurjLmBNRwUMHBCgBTW4TuJdS.m" },
  { name: "Nhà sách Đông Tây", slug: "nha-sach-dong-tay", email: "nhasachdongtay@bookom.vn", password: "Nhasachdongtay123@", hash: "$2a$12$rGBBdT23YQtktTZsPwulrel/4r.oqoZoQ4loo0d.q0PVFuuNsu55u" },
  { name: "Nhà sách Tiền Phong", slug: "nha-sach-tien-phong", email: "nhasachtienphong@bookom.vn", password: "Nhasachtienphong123@", hash: "$2a$12$x5H3DfFTMAGK5Nfp/Qktz.mWGIHd0eD1rqC/k5SgrtveHHbCUQhH2" },
  { name: "Nhà sách Khai Nguyên", slug: "nha-sach-khai-nguyen", email: "nhasachkhainguyen@bookom.vn", password: "Nhasachkhainguyen123@", hash: "$2a$12$Pw1bwI0iZ.UXDosqMz3iG.rXpxEY9IyrM.hCLoLDrrbAja/uA6EWu" },
  { name: "Nhà sách Trường Tồn", slug: "nha-sach-truong-ton", email: "nhasachtruongton@bookom.vn", password: "Nhasachtruongton123@", hash: "$2a$12$82x3zGeIrZLyclmr/l7vbuD02Y6uzHAK1YORvT7Q9k1MdmocuZvpq" },
  { name: "Nhà sách Hoàng Mai", slug: "nha-sach-hoang-mai", email: "nhasachhoangmai@bookom.vn", password: "Nhasachhoangmai123@", hash: "$2a$12$GAQ2fuFhQRHhhGR.uiUdKe5ECZy4fH/VxIX7h9rkkSh1rgMSksowW" },
  { name: "Nhà sách Tân Bình", slug: "nha-sach-tan-binh", email: "nhasachtanbinh@bookom.vn", password: "Nhasachtanbinh123@", hash: "$2a$12$pv7yWnnI5.AII1Oz6Uz0D.oXFEA7poHGJjTAmRuFzdlkGaUzfW6CC" },
  { name: "Nhà sách Gò Vấp", slug: "nha-sach-go-vap", email: "nhasachgovap@bookom.vn", password: "Nhasachgovap123@", hash: "$2a$12$VKdQ4vLeGS8WbzOHsyPeVemUQxzE0EdRPczmeZT.kel/fbegm0Yeq" },
  { name: "Nhà sách Thủ Đức", slug: "nha-sach-thu-duc", email: "nhasachthuduc@bookom.vn", password: "Nhasachthuduc123@", hash: "$2a$12$wBlHRE/6oTlScDqsZIOQvuDGSHiAIjhikyNElD28ssMTzxTAWgg5." },
  { name: "Nhà sách Hải Đăng", slug: "nha-sach-hai-dang", email: "nhasachhaidang@bookom.vn", password: "Nhasachhaidang123@", hash: "$2a$12$V59RZd9kSbNjJ3sEg59ma.g6FFvVqmQLtm6lr9A.4aPtkL4KkyJcy" },
  { name: "Nhà sách Bình Thạnh", slug: "nha-sach-binh-thanh", email: "nhasachbinhthanh@bookom.vn", password: "Nhasachbinhthanh123@", hash: "$2a$12$6.bI72JqtPT9Dt37YAN2A.pcx1b0wE2SnfKVHIQwGQdOw21AYIHxy" },
  { name: "Nhà sách Phú Nhuận", slug: "nha-sach-phu-nhuan", email: "nhasachphunhuan@bookom.vn", password: "Nhasachphunhuan123@", hash: "$2a$12$YVp3IstZWpW0k90peVTDsuopKXSdCPTuQT0jqHct3b6pVIEwOUKBG" }
];
