POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Khai phá dữ liệu Data Mining",
  "author": "Nhóm 4 người",
  "description": "Sách hướng dẫn làm đồ án",
  "price": 250000.0,
  "stockQuantity": 100
}

### Lấy chi tiết sách có ID là 1
GET http://localhost:8080/api/books/1

### Xóa cuốn sách có ID là 1
DELETE http://localhost:8080/api/books/1

### Cập nhật cuốn sách có ID là 1 (Đổi giá và số lượng)
PUT http://localhost:8080/api/books/1
Content-Type: application/json

{
  "title": "Khai phá dữ liệu Data Mining (Tái bản)",
  "author": "Nhóm 4 người",
  "description": "Bản cập nhật mới nhất cho đồ án",
  "price": 299000.0,
  "stockQuantity": 50
}



### ================= BẢNG THỂ LOẠI (CATEGORY) =================

### 1. Thêm một thể loại mới (Ví dụ: Sách CNTT)
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Sách CNTT",
  "description": "Các sách về lập trình, phần mềm và hệ thống"
}

### 2. Thêm một thể loại thứ hai (Ví dụ: Văn học)
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Văn học",
  "description": "Tiểu thuyết, truyện ngắn, thơ ca"
}

### 3. Xem toàn bộ danh sách thể loại
GET http://localhost:8080/api/categories

### Thêm sách mới có gắn Thể loại (Sách CNTT - ID 1)
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "description": "Sách gối đầu giường cho Coder",
  "price": 350000.0,
  "stockQuantity": 20,
  "category": {
    "id": 1
  }}

### =========================================
### TEST TÍNH NĂNG AUTH (ĐĂNG NHẬP / ĐĂNG KÝ)
### =========================================

### 1. Đăng ký tài khoản mới
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "scu",
  "passwordHash": "hehe@1337"
}

### 2. Đăng ký lại tài khoản trùng tên (Test lỗi)
POST http://localhost:8080/api/auth/register
Content-Type: application/json
git
{
  "username": "scu",
  "passwordHash": "123456"
}

### 3. Đăng nhập đúng thông tin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "scu",
  "passwordHash": "Scu123"
}

### 4. Đăng nhập sai mật khẩu (Hacker test)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "scu",
  "passwordHash": "Scu"
}